####
# Env vars are, in order:
# DEPLOY_KEY
# CAPISTRANO_SERVER
# CAPISTRANO_DEPLOY_USER
# CAPISTRANO_DEPLOY_PATH_TO_SSH_KEY
# CAPISTRANO_STAGING_DEPLOY_TO

language: ruby
cache:
  bundler: true
  directories:
    - /home/travis/.rvm

rvm:
  - 2.1.5

before_script:
  - mysql -e 'create database footprints_test;'
  - cp config/ci.database.yml config/database.yml
  - cp config/mailer.yml.example config/mailer.yml

script: bundle exec rake

deploy:
  script:
    - openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -out config/deploy_id_rsa -d -a
    - bundle exec cap production deploy

stages:
  - name: deploy
    if: |
      branch IS master AND \
      env(TRAVIS_PULL_REQUEST) IS NOT true

env:
  global:
  - secure: Q0nhdXwDBW3WXI0MjnjYBflOKjxDsSSgijD7G67rZSNgcT68g8WGRa1nMx1TBjVTwuAy3heqVZlUlu9eri6ypnyi18YVY0cB6R6gY4BjOOcv15QkFPzY1Xtv1BM0FkVtCU4/Q7APWdgmXCQ75dYWP6uSs5COadxRoh3cLunsjPiYD7T3HV+zn7Fr3fZn940BcS7Hre0G1Hf64No6SV5duB8bJ9f4fTHYUCmikIw84rM9Prz7AUZJA4NTCKas2V5MSR6yO3IJLfaPv65hE1VLWlwdrPoyP+odbTrOs4FC7XSiuw1Zf2jgUnk4LEeRQKwO6mjG0FSWm9nn3cTqmOgkBN9748Nm2tTJPXAL3tszC6BQARdDzmxiZ/FHjspTYe4W4o3CJqQI1rW+zwjBn6mGwfnrQp4Kh0TSxGGptbqb5hNrcGacy13FQWx767aYGpf+MQzgujy8UIBKl0+bYegx2aMMTyiGlif8vYBzk9tuUYhKdViyJ0fTiOR/v9Ic8QmoelySStwKwP/R8s4hMVQBtSL+z9XHWnB6p16sZ/EMOTWVBpxMOxlahovn+1iDUjG1e5Y07fLb/AeuvHqqUTuaoOFFq07i5g7RJDtDvvn6BUVC5nNy9aY4bOdLrQKbsUU9rczi5PUhu7Q+qBa5EZ7xUo6/GMYj19Fkn0F7l7Dym+c=
  - secure: WwulkIAfi0An/2Os/PSeUbgFKy5aTNRfC7WfbUaYH+Bt0iCP5MDIxKuOSVkz2ToMls0ZiFmcw2TdHMMjTV9P5dAsPMBCZ4UxIVqk15eQcHrpzH9c5pFh/UK1J6wwQC//mNpjSnxb+0UhdllPz+yRq4P192ajB0vsyHXCsjArGwHj3ArlN4laOrDjfVsydyPVsTXo/PatDrhapWmm2poBlqDAiajgwSMEIAkvMiYJjBmGqZohu3tiiqkTdJ/3ZOhDo+xHi5PfCcllocpEGG/TyRbdzxEJ2UnAHWmuadAIncoH36ACTRPhI/eNboxKcWPjF3P0gwbmdO1PSlv4hksj4HePIbUIdIEsA7FxgLMnlSEXMk/YTV9hKN0EY8ftrZyzjh2tTMfTmiDOVAeckMRcp2kPYfTVsGybWE+fuYIH3AIY3gWGI/87a7arBMY+Cfal1Vxzi9Q6UuV7oXGbVNIA74YXuu/rFQgfA+942z6ua5CNGAhhqCef65Kg4HlucyLyNKoq/62nVYZW9HDJczsPirHbuuSDut01XieHoqCghscRpMICc3YTTHAas7XPB9JLbBmgjIqonFHgiziGOCMq6IgpdXM7H7gNj72V8z0Dkh670ucNOQ5H41CoKqB5+lVD5laTtzi+U5VKv4sF39JHCmIY+yW3uAdjihsXLVGMgos=
  - secure: lZGr/+RGsMncmPDB4IjsKg8QctSSh2y7OjJ/Xs0DHsOmfX0BqPLedT3a//Zh+6B+uJ2PDhPRQ4qdcb58v9fX0rzzFJonqyftQuIj6vC2eHimG0MaX3OSxKZHZQ7Ylo7UBWsAAeJWQrTanihJ+RXSzIM/xi9tMjVDMQAZLbRKTL9aaCGpHzUrNKTZJndBDEiIuNgDDqeHnGkVPi9mbHF/giThK6zESniEm+FribVUdzkEuNAysZM2L7faIDNbHCv17vpnCKEwI+Bk74bKJv6PfVL/1cgpW1+sSWdtbUzxqKhlfMo/KDV+5XLM2Lrqg1e+EAauT7dcX8RiIpTouAiuBjBo8NvdV9QtBMPcO8qwwmanzoICdxImAI2rMQIMJxiyRt0U5Ucy8DLpvnwLujqlVfWXK1O0WxZDdBX30V7UKmrS5PdrScsTc13tP4ryfi80CQIqJwJF93vSYVWE4zyX2jHYN/7UCd8YZLaNcpi+tTJfoST5M4g8Jr67TUhS4sBkVNpbWgmLGbR+7Ren4K7AE//nXYYuzY57yx6cPKufckRJbKzankTH/ISjmvxHpuiYJV3SoGVHN9rVimJTa+pqXTu68AlmngKnSsrL/J6fXwGhJt3wRwKSOvnXrC70pXpOf316tBwtdSsFcBAHG8snVJuzC6wqySQWkV9ifH+55ME=
  - secure: aYx+9kQ12oC3mgJD0+UgKVk3hNAOk4U4UZ4yjcER0vDA5foyucgZFzBHTaS/JtQplUn/allEWRo3+6OUrhZzDifMCzZtLEKs2rWhBT/Qbn189E17qyz5OnuWbOgu3FHpV86yMLbLu/6zAZIDg+4uQuNnP4QD2ocQLxn/3gpC4YogcruR9EDviD7tAkz88Wb1y7Ha7rFot/qL3QL3X6nl0CmuF6hcH3AtO+lUStAvV/bQ0derEjadINtlo6+M3VL5bjzFSCQsfwbDeSNPlbK4mdTFVXd8X90yfEYEiYonNar1QKNTt5ZaJR0bl3oPngYclhBh0N9DxrR3njf0n4tnmf1kz9Qtqwo1uzX5n6/tl/JMvfFkhVQo416zf7hFudnHO2xc5MCidgnC+uJESECC+KvaUXTJRSUWYQnjKlIiEWTfxw0KBVR21kBU0Uh2AmQAo6ibOynG9RMVPzjosH9aRTNPlWW0cyL9ncBcc6T68C30AiGvJORsxQ/bFy69pLbAiNsDuNkACP+VxW6OtTk6SE4nnBETaVeWTmCKD3lEL1tGkwl9+2iquGutc9PtOX4YPPa+so+yZb+E23s2NTnX39dNAUZh0h8Soe4PqvArIEjwHJX4YQ/lG/g0bX9NGBrbtI627ICdAqJ9mWvupA4y+2R1o6XKLjnoJPErv/7Uh7o=
  - secure: Ia3ZAoFyGTS8fMEZwbUvXjeQeVyFut3PlkxtTS+XXVj9KnBK4Rb6viBWWU9Muv4pbQqcur5/HhHR7lFioXEuoUtTGkMrawFGEIP/WyeufQbiSwpF1OQyb5G2EinFctTTJhcNhHHeYVy5vwOxCpRjYwqExKS4RAKzCavOFQzINy0wDmn1LF0RXt3cA/KE0PBc5jaGaY8qRtXteAQ+Bao7S9j2K3ayzyGlU7FuQbUVP/10+1Rr7qDqdZRNTx+Yw9GY+IlAjP3IAfMyWVNcP+93aALmuYLZBhROIq64zDFHX7Lz3V6kinS8uCPQ4jUaWl9dHDry6YT6iKzzXL1pQfZdlzGrylSrkU1X+cdVEz/TienN8EBzTwPNePmVZ+NZAwGcsrgII0/PZNNJ3fdJSezfSyurHFpH9wwakVCkIhG3e/BmuHQHUfhdA0HUwMsF8yykFFUTpTWsXHqx7tlQGAxu9cpaJXNPwMnRM8aL9uKZI87BjAiZ8mlGbeNK2SvvzG8kcE0CdzjrYmZEnPEf9IQbDyGiFb7KJ4Brhur3c65bTf/Fjn87sTGJJkCAkEfn7dc2e00alqGg+U3A5TZJ5Z1NcjcPkufOV5+ukdZ7rT8u0JNeui4pxvZ2LnY2Lp96euFBB+cjcMLgRvdwP3cCWkdyjLkaR6jpz6LhGXQomGZfmok=
