####
# Env vars are, in order:
# DEPLOY_KEY
# CAPISTRANO_DEPLOY_USER
# CAPISTRANO_DEPLOY_PATH_TO_SSH_KEY
# CAPISTRANO_PRODUCTION_DEPLOY_TO
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

language: ruby
cache:
  bundler: true
  directories:
  - "/home/travis/.rvm"
rvm:
- 2.1.5
install: bundle install --jobs=3 --retry=3 --without deploy production
before_script:
- mysql -e 'create database footprints_test;'
- cp config/ci.database.yml config/database.yml
- cp config/mailer.yml.example config/mailer.yml
script: bundle exec rake
jobs:
  include:
  - stage: test
  - stage: deploy
    script: skip
    deploy:
      provider: script
      script: "./travis-deploy.sh"
stages:
- name: test
- name: deploy
  on: |
    branch IS master AND \
    env(TRAVIS_PULL_REQUEST) IS NOT true
env:
  global:
  - secure: VFPTYjs9qySaJ5eE3w63gSfpcKIfFTcR4MxgJQUB5J+uEAsuDGFXFyiJkJSEwT6Y4u46KsA+uMeQ8f9NdYpfx8EpytJ5UYZzJgo5XdmGftggy4rQHkz3FLLlHBDtJGIoVTIJIjJKb9g6IzrX/yx/YGUX34aNrOh+LaJDIDo7bLZx6TZ+1QXhIWF/t2HG8wDL0GD0gyezt5tqxiPObKFQc/XUr1fKvbdrE4sUqVa+45JaKXcfuYWDwjI0xXrEMOSBp10v/jClD17HBKOibbnTk8D5iWuJdPIWZoaRRXNGanPv80UlarEG3E7NPoss5kVc3fkrmL5r1z73LQc6CZvBOkzJ0K6Dnf+Wylw8r2nHV7D3Ek1cf/jTeVagLS23ZhvqVzHRPAuo6jA9ZemJxo7uDM7qKSIcfaPhf4WKFDaevEQHOqTCBYuQ3Xt4yj7YPFsMlfMUUm7G6ZH7t70OwpG6CCYxDdD+BeNboC60dGK5ijqGhE5FyBunO4J+ZAEThP4nsMNGjI5H2osv0J0Z46Drgskf3haXPbdTUlpGkbFhvTUt0W/B+YjDSYi60ukM7S0y2uPFPi7c4Zcm9+oUR6fJ7vDXp9ZjpR4mKbFyexpcO2yRdOgrogTJHK5iOJhpqi7wtzb0xS2N3XLjgpRDtihtDsNTlf8sij0Zz+Gfra43RR0=
  - secure: xHh+xMvA6xbUufBmmyNsDEZG4ZGpVIRK+UeRBSASaseEVlKmbPlHOnGDbwhZxhCyk4/95CBybZyGMJvatsD/buqoSo3pjRwaRzANtHsmmj90LQ6749H+2t0wblKJEvmZ48B7i9Ix1m11uCged3YeYuyGjVFYvigY5ZvyNdV+UX3csEKawPX3kX2XHwSdxwRAsV8s/bqcx4L46hL16/dLLW74U6J2lzAuG8YATm9MEPez04h5b29c6GDceDahrnNrLhcK83OhIafpVdXzjxYLzqrx527kUC8jF0MXkdKczkCggDAHL+GV0MHJKhct/ONL7CDrcWPt90ButmLyxrpyBDublE0KnIXJHe5KtOanFLkstQZG0cf6KBHACVbDTTodhwMUZ7UMgsMusZyRuEBdFctQvMuLAFqGtVmSjestDCSFhogbWc34alWvuvsYeaxdPTGOBqUwjhhlaDldw22hN8SBgPEdvrkikYJDxE8KkRH1x9UByT4o9XvGDLBYr3CPZcQNMakf0pDh88D/UhHfzujOAm5vOEITlLETObfcW6FppHdV5WRFiQqVmuKqekmuwqUzgFY9g1o//OyUv/50XulbIyct2UzGOkiSrMDp7PIBSO5J71Qws20WI5iG4VodlmJ+KeLkz7eC7vL4g6m79aNNV1lcvJh33uv//PLk5fE=
  - secure: aYx+9kQ12oC3mgJD0+UgKVk3hNAOk4U4UZ4yjcER0vDA5foyucgZFzBHTaS/JtQplUn/allEWRo3+6OUrhZzDifMCzZtLEKs2rWhBT/Qbn189E17qyz5OnuWbOgu3FHpV86yMLbLu/6zAZIDg+4uQuNnP4QD2ocQLxn/3gpC4YogcruR9EDviD7tAkz88Wb1y7Ha7rFot/qL3QL3X6nl0CmuF6hcH3AtO+lUStAvV/bQ0derEjadINtlo6+M3VL5bjzFSCQsfwbDeSNPlbK4mdTFVXd8X90yfEYEiYonNar1QKNTt5ZaJR0bl3oPngYclhBh0N9DxrR3njf0n4tnmf1kz9Qtqwo1uzX5n6/tl/JMvfFkhVQo416zf7hFudnHO2xc5MCidgnC+uJESECC+KvaUXTJRSUWYQnjKlIiEWTfxw0KBVR21kBU0Uh2AmQAo6ibOynG9RMVPzjosH9aRTNPlWW0cyL9ncBcc6T68C30AiGvJORsxQ/bFy69pLbAiNsDuNkACP+VxW6OtTk6SE4nnBETaVeWTmCKD3lEL1tGkwl9+2iquGutc9PtOX4YPPa+so+yZb+E23s2NTnX39dNAUZh0h8Soe4PqvArIEjwHJX4YQ/lG/g0bX9NGBrbtI627ICdAqJ9mWvupA4y+2R1o6XKLjnoJPErv/7Uh7o=
  - secure: bBY4kJHC150TOTGMF6IwWK6d14YVOZIEQqdP9R31KQ1jewSMi+/Bih3nF4UxV0ArdnmLdGNHl2+lecR1bW6Rbu5NZT6FNiJOcFzP+c/zjxt47YnC/nNMoVJVUTQ3VABMZi14Meqz2NBCD8tyYFrj8+17Udx8YtFh5MWWEZUhWdFV9RmE4DvNbdjjrnIid6C1kjUkgWIFLE1ukmb+hEelzLwTLUc4V66jDTPrxmDp8n2HscU/yKTH8t5UdIuI0Lddz7zgbZ0uiLI4WQQgoJql1SpE1lca/DNE/Ixsl6J60EhddU04JR0WIdR2gSjp4euUkteFpowdqL3yN49HH7OA/QTcyCkiqvolvEaepgDzZOeVZtE2FIZSOt8hjzbMnChzBlrkZJm7UZ7amBczMslRUekWqCVQKt+kC+GkqYtCevuKoQH0rM47+iOR5iUlVAGSpPY8Grh1jd4A/IaFvT7PukjHMCPnJ84CGjS7gmR0AqvUVwt2fRFqOvtiH7RtX9oEVDPOVwEn1J8ih0Xvcg+qnWDzdtURJqn6eHnDS7AhyXb2vCAUTnTAXV1LSPA5YHmK84e54XrZTtLpBVGyu5yp8EOdknikf3wxBZiTHVsPN0VBxskyxfZa+2TNwd2Uws002ItA5HclLo3Z9K8ZP822Nu5lIfD9/jopszxOYnXss/U=
  - secure: AGeZLeJkOM2gIKLlXenmGe+hRZo6eNeIkFo4xGt7vwqA12T7l3Fys779vlAepERyn75DtCLKGe6nmktzfxD2LQyw/gqqu6A+YdXD9by38kOuyST1NBKR2j8liGjCBfZpRnfKLrRTU+0rj0erayP8Q6Kk/yIRDypcc7qDFb30aLblw5DPiBJaBBXwshszuz9EWCra4k1QKfjofC1EcdoPkfxJU6IffjEnOpXoKHYcMjYEZhFUJga3pJ58dYs4s8RmdEbUObE7cPI12CdlShDxBusZr1jlMI3VRYBbt+58LODXs8mgOtL7cnBAsvKNoznJqiNzh5PzVFxCHwatHJeexjTh3DQp3uHLCgJnO0Zrq2qhcGQat8WNHN5V51dx1CCCYMTFUtc7qXPrL8+477Hq9G4P1Nq9F9tDoDfAtpaZV0WmQRmH+PLAFn1vTm0The0V+xFkJIE/jnm2nIARO/TDTFcxukKDIf7rfyx4kNZO1auoxM4B2/ripXfJQxpvXaRLoDT6HZbfvySuchmbTP0xO3uUtqAx4QxuGDnWiKhTWUIDtD43hxWjVOPKqhbIDUONr31BcaewDmSzGwep4jETV2Bb+Nk740HKN6528rMUSf+6ibBEyGhBGTrb/DT6hE6YgCL+buO224VZhPoFSplPV3e6mEEZcateZFrMr9LQRgk=
  - secure: fc7G68uPqyhqVABGj408ykAHwuFyb+lCHj+5HCH0xih5kcIgfbDzuoIv4kpyr+bPtcpyWyagdHK6uIcFR6Hfbhq2TS/2ew4ccsORgEh5Q4F15o1N4ltKzkWSeCVyMCU7Dh7+OhEL+5hCkEaOmyR5pb2UsU4uKYJq99rv9i5HZr95ebd3tVDbKfqd87hlFAyMfDt4Un+4TSu7oWvNvHrm1XgqSXiEA0NMh7Tt2mfRyHW9KL6tAwmvIjqPz3GUlW0LmlzNMWqkcD1Z0RCKiIDEarh1I7Y/S9opz0lLWyB7tHExRg8PG59PWLobeveFSJilcLGWbx9uD0mqX7YlgGoOBIcPAKDxQknUORsW/vmbUola/brfObFCuByjs56xlnT8yV2G3iaFHOClXrGcSDY75WyKspz7XoZ6vBWpTTS+qxtKjEEPEkkUmSR08AJCm9C4Jz/khTIVnfEBriEONxkjUw45uPG3KHXIV3YDozgOxUdViZ2hZT3MJGkZA/KFp7+mz4s8b3365WP01xPsFyD+mOUQD/Slcl2aXnrZSSnkxEGawo141vxOK7inJj7gb2cM88nG5zZRWbtd8AfGVNfsIetzP/npLKMmABYs1qS3V2zF7bFEfPG2LrstxcF6vuLPLflb2ki6cIDwQ7DYJWGWcflDoR954dC4HCUb88R6siI=
