version: '3'
services:
  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # Allow support for irb, pry, etc
    stdin_open: true
    tty: true
