development:
  client_id: <%= "'#{ENV['OAUTH_CLIENT_ID']}'" %>
  client_secret: <%= "'#{ENV['OAUTH_CLIENT_SECRET']}'" %>

local:
  client_id: <%= "'#{ENV['OAUTH_CLIENT_ID']}'" %>
  client_secret: <%= "'#{ENV['OAUTH_CLIENT_SECRET']}'" %>

staging:
  client_id: <%= "'#{ENV['OAUTH_CLIENT_ID']}'" %>
  client_secret: <%= "'#{ENV['OAUTH_CLIENT_SECRET']}'" %>

production:
  client_id: <%= "'#{ENV['OAUTH_CLIENT_ID']}'" %>
  client_secret: <%= "'#{ENV['OAUTH_CLIENT_SECRET']}'" %>
